# Generated by Django 3.2.2 on 2021-05-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playlist_creation.uuidmodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('provider_urls', models.JSONField(default=dict)),
                ('playlists', models.ManyToManyField(to='playlist_creation.Playlist')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('playlist_creation.uuidmodel', models.Model),
        ),
    ]
