# Generated by Django 3.2.4 on 2021-08-03 15:02
from django.contrib.sites.management import create_default_site
from django.db import migrations


def create_privacy_policy_flatpage(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site = Site.objects.first()
    if not site:
        create_default_site(None)
        site = Site.objects.first()

    FlatPage = apps.get_model("flatpages", "FlatPage")
    page, created = \
        FlatPage.objects.get_or_create(url='/privacy-policy/',
                                       defaults={'title': 'Privacy Policy'})
    if created:
        page.sites.add(site)


def delete_privacy_policy_flatpage(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")
    FlatPage.objects.filter(url='/privacy-policy/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_creation', '0001_initial'),
        ("sites", "0002_alter_domain_unique")
    ]

    operations = [
        migrations.RunPython(create_privacy_policy_flatpage,
                             delete_privacy_policy_flatpage),
    ]
