# Generated by Django 3.2.2 on 2021-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_creation', '0002_auto_20210509_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='provider_urls',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(related_name='tracks', to='playlist_creation.Playlist'),
        ),
    ]
